### ISSUE TITLE
implementation API coopcycle demande de course tarifs

### ISSUE THREAD

**Issue by PasLoin** [couleurmate/molenbike#10]
process demande de devis client et acceptation course via api

**Comment by couleurmate** [comment]
t'as l'URL de l'API en question ?

**Comment by PasLoin** [comment]
https://demo.coopcycle.org/api/docs

**Comment by couleurmate** [comment]
`POST` api/order ?

**Comment by PasLoin** [comment]
F.B.I (fausse bonne idée) car site statique. Donc soit passer par 
https://github.com/coopcycle/coopcycle-web/tree/master/src/Form
Ou utiliser / améliorer : https://github.com/coopcycle/coopcycle-plugins
