### ISSUE TITLE
Translate NL FR marketing-site-features-headline

### ISSUE THREAD

**Issue by PasLoin** [couleurmate/molenbike#17]

**Comment by couleurmate** [comment]
ik versta nie ? C'est déjà traduit

**Comment by PasLoin** [comment]
Président à assistance électrique
“Delta Trike” icon by eric poscher, from thenounproject.com
Raphaël

Manager de pédaleurs
“front loader” icon by eric poscher, from thenounproject.com
Sacha

Mécanicien cargo
“Diamond” icon by eric poscher, from thenounproject.com
Marie

Gestion des ressources roulantes
