### ISSUE TITLE
Carousel not working on https

### ISSUE THREAD

**Issue by couleurmate** [couleurmate/molenbike#39]

**Comment by couleurmate** [comment]
Only on mobile devices

**Comment by PasLoin** [comment]
I have the same issue on Firefox and chrome ; https://developer.mozilla.org/fr/docs/S%C3%A9curit%C3%A9/MixedContent : my browser block it : Aucune des empreintes « sha256 » de l’attribut « integrity » ne correspond au contenu de la sous-ressource.

**Comment by PasLoin** [comment]
issue also for "notre charte" et "nos statuts"

**Comment by couleurmate** [comment]
ok solved but align is messed up
